# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopLevelTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tlp_text', models.CharField(max_length=50)),
                ('tlp_description', models.CharField(max_length=800)),
            ],
        ),
    ]
