# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteframe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=50)),
                ('article_author', models.CharField(max_length=50)),
                ('article_body', models.CharField(max_length=5000)),
                ('article_pubdate', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
