# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteframe', '0005_auto_20171205_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Fruit',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='place',
        ),
        migrations.RemoveField(
            model_name='waiter',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_author',
        ),
        migrations.AddField(
            model_name='article',
            name='article_author',
            field=models.ManyToManyField(to='siteframe.Author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='topleveltopic',
            name='tlp_description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='topleveltopic',
            name='tlp_text',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='Waiter',
        ),
        migrations.AddField(
            model_name='article',
            name='article_tag',
            field=models.ManyToManyField(to='siteframe.Tag'),
        ),
    ]
