# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteframe', '0007_author_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_author',
            new_name='article_authors',
        ),
    ]
